// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqTzg_hM1i_JkzNcKvZ2fFV3BcF8thQI8',
    appId: '1:488723905822:web:f454dfa86896a00c569d0f',
    messagingSenderId: '488723905822',
    projectId: 'patas-app',
    authDomain: 'patas-app.firebaseapp.com',
    storageBucket: 'patas-app.appspot.com',
    measurementId: 'G-4MFJ6PV002',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3JMtMhV8-zblo5rByKm6VH74ShikE-6A',
    appId: '1:488723905822:android:ab38930670a32491569d0f',
    messagingSenderId: '488723905822',
    projectId: 'patas-app',
    storageBucket: 'patas-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTZcQ4oGR0u7Nq0VJysPhee-t-4q-NMIM',
    appId: '1:488723905822:ios:d1bc349b8eb42a00569d0f',
    messagingSenderId: '488723905822',
    projectId: 'patas-app',
    storageBucket: 'patas-app.appspot.com',
    iosClientId:
        '488723905822-rfd1jfb943te2f3mit4pl4pbp3bb1mrp.apps.googleusercontent.com',
    iosBundleId: 'com.origemstudio.patas.dev',
  );
}
